//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinematic.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Literals() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kash.Core.Sandbox.Resources.Literals", typeof(Literals).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sistema de venta de entradas..
        /// </summary>
        public static string AppSummary {
            get {
                return ResourceManager.GetString("AppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cinematic.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Butacas disponibles.
        /// </summary>
        public static string AvailableSeats {
            get {
                return ResourceManager.GetString("AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sesiones disponibles.
        /// </summary>
        public static string AvailableSessions {
            get {
                return ResourceManager.GetString("AvailableSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Volver.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error en la compra.
        /// </summary>
        public static string BuyError {
            get {
                return ResourceManager.GetString("BuyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eliminación.
        /// </summary>
        public static string DeleteSession {
            get {
                return ResourceManager.GetString("DeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fila.
        /// </summary>
        public static string Entity_Seat_Row_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Seat_Row_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Butaca.
        /// </summary>
        public static string Entity_Seat_SeatNumber_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Seat_SeatNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Estado.
        /// </summary>
        public static string Entity_Session_Status_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Session_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Inicio de la sesión.
        /// </summary>
        public static string Entity_Session_TimeAndDate_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Session_TimeAndDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Localización.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nueva sesión.
        /// </summary>
        public static string NewSession {
            get {
                return ResourceManager.GetString("NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to -- No hay sesiones disponibles --.
        /// </summary>
        public static string NoAvailableSessions {
            get {
                return ResourceManager.GetString("NoAvailableSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to -- No hay datos que mostrar --.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to asientos seleccionados.
        /// </summary>
        public static string SelectedSeats {
            get {
                return ResourceManager.GetString("SelectedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vender.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fecha de venta.
        /// </summary>
        public static string SellDate {
            get {
                return ResourceManager.GetString("SellDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sesión.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Detalles de la sesión.
        /// </summary>
        public static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edición de la sesión.
        /// </summary>
        public static string SessionEdit {
            get {
                return ResourceManager.GetString("SessionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sesiones.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Va a eliminar el elemento. ¿Está seguro?.
        /// </summary>
        public static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string TicketId {
            get {
                return ResourceManager.GetString("TicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to P.V.P..
        /// </summary>
        public static string TicketPrice {
            get {
                return ResourceManager.GetString("TicketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Venta de entradas.
        /// </summary>
        public static string TicketSelling {
            get {
                return ResourceManager.GetString("TicketSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Venta finalizada.
        /// </summary>
        public static string TicketsSelled {
            get {
                return ResourceManager.GetString("TicketsSelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string ValueObject_SessionStatus_Cancelled_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Cancelled_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cerrada.
        /// </summary>
        public static string ValueObject_SessionStatus_Closed_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Closed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Abierta.
        /// </summary>
        public static string ValueObject_SessionStatus_Open_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Open_DisplayName", resourceCulture);
            }
        }
    }
}
