//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinematic.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    Clase de recurso fuertemente tipada para buscar cadenas localizadas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Literals() {
        }
        
        /// <summary>
        ///    Devuelve la instancia de ResourceManager en caché que usa la clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinematic.Resources.Literals", typeof(Literals).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Reemplaza la propiedad CurrentUICulture del subproceso actual para todas
        ///    las búsquedas de recursos que usan esta clase de recursos fuertemente tipada.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Acerca de.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Sistema de venta de entradas para sesiones de cine.
        /// </summary>
        public static string AppSummary {
            get {
                return ResourceManager.GetString("AppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cinematic.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a DotNetters Zaragoza.
        /// </summary>
        public static string AppVendor {
            get {
                return ResourceManager.GetString("AppVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a contacto@dotnetters.es.
        /// </summary>
        public static string AppVendorEMail {
            get {
                return ResourceManager.GetString("AppVendorEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a http://dotnetters.es.
        /// </summary>
        public static string AppVendorWebSite {
            get {
                return ResourceManager.GetString("AppVendorWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Butacas disponibles.
        /// </summary>
        public static string AvailableSeats {
            get {
                return ResourceManager.GetString("AvailableSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Sesiones disponibles.
        /// </summary>
        public static string AvailableSessions {
            get {
                return ResourceManager.GetString("AvailableSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Volver.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Error en la compra.
        /// </summary>
        public static string BuyError {
            get {
                return ResourceManager.GetString("BuyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cambiar estado.
        /// </summary>
        public static string ChangeSessionStatus {
            get {
                return ResourceManager.GetString("ChangeSessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Eliminación.
        /// </summary>
        public static string DeleteSession {
            get {
                return ResourceManager.GetString("DeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Fila.
        /// </summary>
        public static string Entity_Seat_Row_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Seat_Row_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Butaca.
        /// </summary>
        public static string Entity_Seat_SeatNumber_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Seat_SeatNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Estado.
        /// </summary>
        public static string Entity_Session_Status_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Session_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Inicio de la sesión.
        /// </summary>
        public static string Entity_Session_TimeAndDate_DisplayName {
            get {
                return ResourceManager.GetString("Entity_Session_TimeAndDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Localización.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Nueva sesión.
        /// </summary>
        public static string NewSession {
            get {
                return ResourceManager.GetString("NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a -- No hay sesiones disponibles --.
        /// </summary>
        public static string NoAvailableSessions {
            get {
                return ResourceManager.GetString("NoAvailableSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a -- No hay datos que mostrar --.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Abrir.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a asientos seleccionados.
        /// </summary>
        public static string SelectedSeats {
            get {
                return ResourceManager.GetString("SelectedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Vender.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Fecha de venta.
        /// </summary>
        public static string SellDate {
            get {
                return ResourceManager.GetString("SellDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Sesión.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Detalles de la sesión.
        /// </summary>
        public static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Edición de la sesión.
        /// </summary>
        public static string SessionEdit {
            get {
                return ResourceManager.GetString("SessionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Sesiones.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Soporte.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Va a eliminar el elemento. ¿Está seguro?.
        /// </summary>
        public static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Ticket #.
        /// </summary>
        public static string TicketId {
            get {
                return ResourceManager.GetString("TicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a P.V.P..
        /// </summary>
        public static string TicketPrice {
            get {
                return ResourceManager.GetString("TicketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Venta de entradas.
        /// </summary>
        public static string TicketSelling {
            get {
                return ResourceManager.GetString("TicketSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Venta finalizada.
        /// </summary>
        public static string TicketsSelled {
            get {
                return ResourceManager.GetString("TicketsSelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Navegación.
        /// </summary>
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cancelada.
        /// </summary>
        public static string ValueObject_SessionStatus_Cancelled_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Cancelled_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cerrada.
        /// </summary>
        public static string ValueObject_SessionStatus_Closed_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Closed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Abierta.
        /// </summary>
        public static string ValueObject_SessionStatus_Open_DisplayName {
            get {
                return ResourceManager.GetString("ValueObject_SessionStatus_Open_DisplayName", resourceCulture);
            }
        }
    }
}
